---
- hosts: all
  become: yes
  tasks:
  - name: Update package and install httpd
    yum:
      name: httpd
      update_cache: yes
      state: present
  - name: restart httpd after installation
    service:
      name: httpd
      enabled: yes
      state: restarted
  - name: install php
    yum:
      name: "{{ packages }}"
      vars:
        packages:
        - php
        - php-mysql
      state: present
  - name: restart httpd.service 
    service:
      name: httpd
      enabled: yes
      state: restarted
      

